# Generated by Django 5.1.2 on 2025-09-12 14:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('author', models.CharField(default='Henry Oak Reality', max_length=100)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, help_text='Short description for blog listing', max_length=500)),
                ('image_url', models.URLField(blank=True, help_text='Main image URL for the blog post', max_length=500)),
                ('featured', models.BooleanField(default=False, help_text='Featured posts appear first')),
                ('published', models.BooleanField(default=True, help_text='Only published posts are visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('blog_post_id', models.IntegerField(help_text='ID of the blog post being tracked')),
                ('member_name', models.CharField(help_text='Name of the member receiving the link', max_length=200)),
                ('member_email', models.EmailField(help_text='Email of the member receiving the link', max_length=254)),
                ('member_phone', models.CharField(blank=True, help_text='Phone number of the member', max_length=20, null=True)),
                ('crm_reference', models.CharField(blank=True, help_text='Reference from CRM system', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, help_text='When the link was first opened', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the opener', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information', null=True)),
                ('is_opened', models.BooleanField(default=False, help_text='Whether the link has been opened')),
            ],
            options={
                'verbose_name': 'Blog Tracking',
                'verbose_name_plural': 'Blog Trackings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpenHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Property', help_text='Property title for open house', max_length=200)),
                ('property_address', models.TextField(default='Address TBD', help_text='Full property address')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Property price in dollars', max_digits=12)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('area_sqft', models.IntegerField(blank=True, help_text='Area in square feet', null=True)),
                ('description', models.TextField(default='Property description', help_text='Property description')),
                ('image_url', models.URLField(default='https://via.placeholder.com/400x300', help_text='Property image URL', max_length=500)),
                ('open_house_date', models.DateField(help_text='Date of the open house')),
                ('open_house_time', models.TimeField(help_text='Time of the open house')),
                ('contact_email', models.EmailField(default='abhi.gupta82@gmail.com', help_text='Contact email for inquiries', max_length=254)),
                ('contact_phone', models.CharField(default='+1 (315) 395-8315', help_text='Contact phone number', max_length=20)),
                ('published', models.BooleanField(default=True, help_text='Only published open houses are visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Open House',
                'verbose_name_plural': 'Open Houses',
                'ordering': ['open_house_date', 'open_house_time'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('location', models.TextField()),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField(null=True)),
                ('bathrooms', models.IntegerField(null=True)),
                ('parking_space', models.IntegerField(null=True)),
                ('area', models.CharField(max_length=50)),
                ('site_url', models.URLField(max_length=255, null=True)),
                ('image_url', models.URLField(max_length=255, null=True)),
                ('time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('buy', 'For Sale'), ('lease', 'For Lease')], default='buy', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in dollars', max_digits=12)),
                ('location', models.CharField(max_length=200)),
                ('address', models.TextField(help_text='Full property address')),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('parking_spaces', models.IntegerField(blank=True, null=True)),
                ('area_sqft', models.IntegerField(blank=True, help_text='Area in square feet', null=True)),
                ('description', models.TextField(help_text='Detailed property description')),
                ('image_url', models.URLField(help_text='Main property image URL', max_length=500)),
                ('additional_images', models.TextField(blank=True, help_text='Additional image URLs (one per line)')),
                ('featured', models.BooleanField(default=False, help_text='Featured properties appear first')),
                ('published', models.BooleanField(default=True, help_text='Only published properties are visible')),
                ('contact_email', models.EmailField(default='abhi.gupta82@gmail.com', help_text='Contact email for inquiries', max_length=254)),
                ('contact_phone', models.CharField(default='+1 (315) 395-8315', help_text='Contact phone number', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property Listing',
                'verbose_name_plural': 'Property Listings',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellingContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('property_address', models.TextField(blank=True, null=True)),
                ('property_type', models.CharField(blank=True, max_length=50, null=True)),
                ('estimated_value', models.CharField(blank=True, max_length=50, null=True)),
                ('timeline', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
