# Generated by Django 5.1.2 on 2025-09-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Henry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload property image (optional if providing URL)', null=True, upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='image_url',
            field=models.URLField(blank=True, help_text='Main property image URL (optional if uploading file)', max_length=500),
        ),
    ]
