# Generated by Django 5.2.5 on 2025-09-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Henry', '0003_blogtracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('author', models.CharField(default='Henry Oak Reality', max_length=100)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, help_text='Short description for blog listing', max_length=500)),
                ('image_url', models.URLField(blank=True, help_text='Main image URL for the blog post', max_length=500)),
                ('featured', models.BooleanField(default=False, help_text='Featured posts appear first')),
                ('published', models.BooleanField(default=True, help_text='Only published posts are visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-featured', '-created_at'],
            },
        ),
    ]

