# Generated by Django 5.1.2 on 2025-09-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Henry', '0004_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('buy', 'For Sale'), ('lease', 'For Lease')], default='buy', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in dollars', max_digits=12)),
                ('location', models.CharField(max_length=200)),
                ('address', models.TextField(help_text='Full property address')),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('parking_spaces', models.IntegerField(blank=True, null=True)),
                ('area_sqft', models.IntegerField(blank=True, help_text='Area in square feet', null=True)),
                ('description', models.TextField(help_text='Detailed property description')),
                ('image_url', models.URLField(help_text='Main property image URL', max_length=500)),
                ('additional_images', models.TextField(blank=True, help_text='Additional image URLs (one per line)')),
                ('featured', models.BooleanField(default=False, help_text='Featured properties appear first')),
                ('published', models.BooleanField(default=True, help_text='Only published properties are visible')),
                ('contact_email', models.EmailField(help_text='Contact email for inquiries')),
                ('contact_phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property Listing',
                'verbose_name_plural': 'Property Listings',
                'ordering': ['-featured', '-created_at'],
            },
        ),
    ]
