# Generated by Django 5.1.2 on 2025-09-10 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Henry', '0005_auto_20250908_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Property', help_text='Property title for open house', max_length=200)),
                ('property_address', models.TextField(default='Address TBD', help_text='Full property address')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Property price in dollars', max_digits=12)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('area_sqft', models.IntegerField(blank=True, help_text='Area in square feet', null=True)),
                ('description', models.TextField(default='Property description', help_text='Property description')),
                ('image_url', models.URLField(default='https://via.placeholder.com/400x300', help_text='Property image URL', max_length=500)),
                ('open_house_date', models.DateField(default='2024-12-01', help_text='Date of the open house')),
                ('open_house_time', models.TimeField(default='14:00:00', help_text='Time of the open house')),
                ('contact_email', models.EmailField(default='contact@henryoakreality.com', help_text='Contact email for inquiries')),
                ('contact_phone', models.CharField(default='+1 (234) 567-890', help_text='Contact phone number', max_length=20)),
                ('published', models.BooleanField(default=True, help_text='Only published open houses are visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Open House',
                'verbose_name_plural': 'Open Houses',
                'ordering': ['open_house_date', 'open_house_time'],
            },
        ),
    ]
