# Generated by Django 5.1.2 on 2025-09-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Henry', '0006_auto_20250910_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openhouse',
            name='open_house_date',
            field=models.DateField(help_text='Date of the open house'),
        ),
        migrations.AlterField(
            model_name='openhouse',
            name='open_house_time',
            field=models.TimeField(help_text='Time of the open house'),
        ),
    ]
