# Generated by Django 5.1.2 on 2025-09-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Henry', '0007_auto_20250910_1955'),
    ]

    operations = [
    ]
