# Generated by Django 5.2.5 on 2025-09-14 19:31

from django.db import migrations


def update_contact_info(apps, schema_editor):
    """Update contact information in existing records"""
    PropertyListing = apps.get_model('Henry', 'PropertyListing')
    OpenHouse = apps.get_model('Henry', 'OpenHouse')
    
    # Update PropertyListing records
    PropertyListing.objects.filter(contact_email='abhi.gupta82@gmail.com').update(
        contact_email='raj.gupta@kw.com',
        contact_phone='(832) 785-0140'
    )
    
    # Update OpenHouse records
    OpenHouse.objects.filter(contact_email='abhi.gupta82@gmail.com').update(
        contact_email='raj.gupta@kw.com',
        contact_phone='(832) 785-0140'
    )


def reverse_contact_info(apps, schema_editor):
    """Reverse the contact information update"""
    PropertyListing = apps.get_model('Henry', 'PropertyListing')
    OpenHouse = apps.get_model('Henry', 'OpenHouse')
    
    # Reverse PropertyListing records
    PropertyListing.objects.filter(contact_email='raj.gupta@kw.com').update(
        contact_email='abhi.gupta82@gmail.com',
        contact_phone='+1 (315) 395-8315'
    )
    
    # Reverse OpenHouse records
    OpenHouse.objects.filter(contact_email='raj.gupta@kw.com').update(
        contact_email='abhi.gupta82@gmail.com',
        contact_phone='+1 (315) 395-8315'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('Henry', '0007_sellingcontact_ip_address_sellingcontact_language_and_more'),
    ]

    operations = [
        migrations.RunPython(update_contact_info, reverse_contact_info),
    ]
