# Generated by Django 5.2.5 on 2025-09-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Henry', '0009_blogpost_image_file_alter_openhouse_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(help_text='Unique customer code (e.g., NAE1495)', max_length=50)),
                ('page_type', models.CharField(choices=[('blog', 'Blog Post'), ('buy', 'Buy/Lease Page'), ('sell', 'Selling Page'), ('open_house', 'Open House'), ('mortgage', 'Mortgage Calculator'), ('home', 'Home Page'), ('contact', 'Contact Page')], help_text='Type of page being tracked', max_length=20)),
                ('page_id', models.CharField(blank=True, help_text='ID of the specific page (e.g., blog post ID)', max_length=50, null=True)),
                ('original_url', models.URLField(help_text='The original URL without tracking code')),
                ('tracked_url', models.URLField(help_text='The URL with tracking code')),
                ('customer_name', models.CharField(blank=True, help_text='Customer name if available', max_length=200, null=True)),
                ('customer_email', models.EmailField(blank=True, help_text='Customer email if available', max_length=254, null=True)),
                ('first_clicked_at', models.DateTimeField(blank=True, help_text='When the link was first clicked', null=True)),
                ('last_clicked_at', models.DateTimeField(blank=True, help_text='When the link was last clicked', null=True)),
                ('click_count', models.IntegerField(default=0, help_text='Total number of clicks')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the clicker', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information', null=True)),
                ('referrer', models.URLField(blank=True, help_text='Page that referred the user', null=True)),
                ('language', models.CharField(blank=True, help_text="User's preferred language", max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Link Tracking',
                'verbose_name_plural': 'Link Trackings',
                'ordering': ['-last_clicked_at', '-created_at'],
                'unique_together': {('customer_code', 'page_type', 'page_id')},
            },
        ),
    ]
