# Generated by Django 5.2.5 on 2025-09-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Henry', '0010_linktracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linktracking',
            name='page_type',
            field=models.CharField(choices=[('blog', 'Blog Post'), ('buy', 'Buy/Lease Page'), ('sell', 'Selling Page'), ('open_house', 'Open House'), ('mortgage', 'Mortgage Calculator'), ('home', 'Home Page'), ('contact', 'Contact Page'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('telegram', 'Telegram'), ('youtube', 'YouTube')], help_text='Type of page being tracked', max_length=20),
        ),
    ]
