# Generated by Django 5.2.5 on 2025-09-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Henry', '0012_openhouse_image_file_alter_openhouse_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linktracking',
            name='language',
            field=models.CharField(blank=True, help_text="User's preferred language", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mortgageinquiry',
            name='language',
            field=models.CharField(blank=True, help_text="User's preferred language", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propertyinquiry',
            name='language',
            field=models.CharField(blank=True, help_text="User's preferred language", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sellingcontact',
            name='language',
            field=models.CharField(blank=True, help_text="User's preferred language", max_length=50, null=True),
        ),
    ]
