# Generated by Django 5.2.5 on 2025-09-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Henry', '0014_alter_linktracking_customer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openhouse',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded image data', null=True),
        ),
        migrations.AddField(
            model_name='openhouseimage',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded image data', null=True),
        ),
    ]
