# Generated by Django 5.2.5 on 2025-09-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Henry', '0015_openhouse_image_base64_openhouseimage_image_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded image data', null=True),
        ),
    ]
