# Generated by Django 5.2.5 on 2025-09-18 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Henry', '0016_propertylisting_image_base64'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(help_text='Upload property image', upload_to='properties/gallery/')),
                ('image_url', models.URLField(blank=True, help_text='Alternative: Property image URL', max_length=500)),
                ('image_base64', models.TextField(blank=True, help_text='Base64 encoded image data', null=True)),
                ('caption', models.CharField(blank=True, help_text='Optional image caption', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary image for the property')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (0 = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Henry.propertylisting')),
            ],
            options={
                'verbose_name': 'Property Listing Image',
                'verbose_name_plural': 'Property Listing Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
