# Generated by Django 5.2.5 on 2025-09-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Henry', '0017_propertylistingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='background_color',
            field=models.CharField(blank=True, help_text='Background color (hex code, optional)', max_length=7),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='font_family',
            field=models.CharField(default='Arial', help_text='Font family (e.g., Arial, Georgia, Times New Roman)', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='font_size',
            field=models.CharField(default='16px', help_text='Font size (e.g., 16px, 1.2em)', max_length=10),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='line_height',
            field=models.CharField(default='1.6', help_text='Line height (e.g., 1.6, 24px)', max_length=10),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='text_color',
            field=models.CharField(default='#000000', help_text='Text color (hex code, e.g., #000000)', max_length=7),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='Rich text content with HTML formatting'),
        ),
    ]
