# Generated by Django 5.2.5 on 2025-09-18 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Henry', '0018_blogpost_background_color_blogpost_font_family_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='background_color',
        ),
    ]
