# Generated by Django 5.2.5 on 2025-09-18 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Henry', '0019_remove_blogpost_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_1',
            field=models.ImageField(blank=True, help_text='Content image 1 - use {{image_1}} in content', null=True, upload_to='blog_images/content/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Content image 2 - use {{image_2}} in content', null=True, upload_to='blog_images/content/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Content image 3 - use {{image_3}} in content', null=True, upload_to='blog_images/content/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_4',
            field=models.ImageField(blank=True, help_text='Content image 4 - use {{image_4}} in content', null=True, upload_to='blog_images/content/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_5',
            field=models.ImageField(blank=True, help_text='Content image 5 - use {{image_5}} in content', null=True, upload_to='blog_images/content/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='Rich text content with HTML formatting. Use {{image_1}}, {{image_2}}, etc. to insert uploaded images anywhere in your content.'),
        ),
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Henry.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Post Image',
                'verbose_name_plural': 'Blog Post Images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
