# Generated by Django 5.2.5 on 2025-09-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Henry', '0020_blogpost_image_1_blogpost_image_2_blogpost_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_1_base64',
            field=models.TextField(blank=True, help_text='Content image 1 (base64) - use {{image_1}} in content', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_2_base64',
            field=models.TextField(blank=True, help_text='Content image 2 (base64) - use {{image_2}} in content', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_3_base64',
            field=models.TextField(blank=True, help_text='Content image 3 (base64) - use {{image_3}} in content', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_4_base64',
            field=models.TextField(blank=True, help_text='Content image 4 (base64) - use {{image_4}} in content', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_5_base64',
            field=models.TextField(blank=True, help_text='Content image 5 (base64) - use {{image_5}} in content', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_1',
            field=models.ImageField(blank=True, help_text='Content image 1 - will be converted to base64', null=True, upload_to='blog_images/content/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Content image 2 - will be converted to base64', null=True, upload_to='blog_images/content/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Content image 3 - will be converted to base64', null=True, upload_to='blog_images/content/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_4',
            field=models.ImageField(blank=True, help_text='Content image 4 - will be converted to base64', null=True, upload_to='blog_images/content/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_5',
            field=models.ImageField(blank=True, help_text='Content image 5 - will be converted to base64', null=True, upload_to='blog_images/content/'),
        ),
    ]
