# Generated by Django 5.2.5 on 2025-09-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raj', '0002_propertylisting_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='image_url',
            field=models.TextField(blank=True, help_text='Main property image URL or base64 data URL (optional if uploading file)'),
        ),
    ]
