# Generated by Django 5.2.5 on 2025-09-14 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raj', '0003_alter_propertylisting_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openhouse',
            options={'ordering': ['open_house_date', 'open_house_time'], 'verbose_name': 'Open House'},
        ),
        migrations.CreateModel(
            name='OpenHouseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Visitor's full name", max_length=100)),
                ('email', models.EmailField(help_text="Visitor's email address", max_length=254)),
                ('phone', models.CharField(help_text="Visitor's phone number", max_length=20)),
                ('message', models.TextField(blank=True, help_text='Additional message or questions', null=True)),
                ('interested_in_buying', models.BooleanField(default=False, help_text='Is the visitor interested in buying?')),
                ('interested_in_leasing', models.BooleanField(default=False, help_text='Is the visitor interested in leasing?')),
                ('preferred_contact_time', models.CharField(blank=True, choices=[('morning', 'Morning (9 AM - 12 PM)'), ('afternoon', 'Afternoon (12 PM - 5 PM)'), ('evening', 'Evening (5 PM - 8 PM)'), ('anytime', 'Anytime')], help_text='Preferred time to be contacted', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('open_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Raj.openhouse')),
            ],
            options={
                'verbose_name': 'Open House Registration',
                'verbose_name_plural': 'Open House Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
