# Generated by Django 5.2.5 on 2025-09-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raj', '0004_alter_openhouse_options_openhouseregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Inquirer's full name", max_length=100)),
                ('email', models.EmailField(help_text="Inquirer's email address", max_length=254)),
                ('phone', models.CharField(help_text="Inquirer's phone number", max_length=20)),
                ('property_type', models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('commercial', 'Commercial')], help_text="Type of property they're interested in", max_length=50, null=True)),
                ('home_price', models.DecimalField(blank=True, decimal_places=2, help_text="Home price they're considering", max_digits=12, null=True)),
                ('down_payment', models.DecimalField(blank=True, decimal_places=2, help_text='Down payment amount they have', max_digits=12, null=True)),
                ('loan_term', models.IntegerField(blank=True, choices=[(15, '15 Years'), (20, '20 Years'), (25, '25 Years'), (30, '30 Years')], help_text='Preferred loan term in years', null=True)),
                ('credit_score', models.CharField(blank=True, choices=[('excellent', 'Excellent (750+)'), ('good', 'Good (700-749)'), ('fair', 'Fair (650-699)'), ('poor', 'Poor (Below 650)')], help_text='Credit score range', max_length=20, null=True)),
                ('additional_info', models.TextField(blank=True, help_text='Additional information about their mortgage needs', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mortgage Inquiry',
                'verbose_name_plural': 'Mortgage Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Inquirer's full name", max_length=100)),
                ('email', models.EmailField(help_text="Inquirer's email address", max_length=254)),
                ('phone', models.CharField(help_text="Inquirer's phone number", max_length=20)),
                ('property_type', models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('commercial', 'Commercial')], help_text="Type of property they're looking for", max_length=50, null=True)),
                ('budget_range', models.CharField(blank=True, choices=[('under-300k', 'Under $300,000'), ('300k-500k', '$300,000 - $500,000'), ('500k-750k', '$500,000 - $750,000'), ('750k-1m', '$750,000 - $1,000,000'), ('over-1m', 'Over $1,000,000')], help_text='Budget range for the property', max_length=50, null=True)),
                ('location', models.CharField(blank=True, help_text='Preferred location', max_length=200, null=True)),
                ('requirements', models.TextField(blank=True, help_text='Specific requirements and preferences', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Property Inquiry',
                'verbose_name_plural': 'Property Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
