# Generated by Django 5.2.5 on 2025-09-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raj', '0006_mortgageinquiry_ip_address_mortgageinquiry_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingcontact',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the submitter', null=True),
        ),
        migrations.AddField(
            model_name='sellingcontact',
            name='language',
            field=models.CharField(blank=True, help_text="User's preferred language", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sellingcontact',
            name='referrer',
            field=models.URLField(blank=True, help_text='Page that referred the user', null=True),
        ),
        migrations.AddField(
            model_name='sellingcontact',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Browser/device information', null=True),
        ),
    ]
