# Generated by Django 5.2.5 on 2025-09-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raj', '0008_auto_20250915_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload an image file (alternative to image URL)', null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='openhouse',
            name='contact_email',
            field=models.EmailField(default='raj.gupta@kw.com', help_text='Contact email for inquiries', max_length=254),
        ),
        migrations.AlterField(
            model_name='openhouse',
            name='contact_phone',
            field=models.CharField(default='(832) 785-0140', help_text='Contact phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='contact_email',
            field=models.EmailField(default='raj.gupta@kw.com', help_text='Contact email for inquiries', max_length=254),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='contact_phone',
            field=models.CharField(default='(832) 785-0140', help_text='Contact phone number', max_length=20),
        ),
    ]
