# Generated by Django 5.2.5 on 2025-09-16 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raj', '0011_alter_linktracking_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='openhouse',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload a main image file (alternative to image URL)', null=True, upload_to='openhouse_images/'),
        ),
        migrations.AlterField(
            model_name='openhouse',
            name='image_url',
            field=models.URLField(blank=True, default='https://via.placeholder.com/400x300', help_text='Property image URL', max_length=500),
        ),
        migrations.CreateModel(
            name='OpenHouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(help_text='Upload property image', upload_to='openhouse_images/gallery/')),
                ('image_url', models.URLField(blank=True, help_text='Alternative: Property image URL', max_length=500)),
                ('caption', models.CharField(blank=True, help_text='Optional image caption', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary image for the property')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (0 = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('open_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Raj.openhouse')),
            ],
            options={
                'verbose_name': 'Open House Image',
                'verbose_name_plural': 'Open House Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
