# Generated by Django 5.2.5 on 2025-09-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raj', '0013_alter_linktracking_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linktracking',
            name='customer_code',
            field=models.CharField(help_text='Unique customer code (e.g., NAE1495)', max_length=100),
        ),
        migrations.AlterField(
            model_name='linktracking',
            name='page_id',
            field=models.CharField(blank=True, help_text='ID of the specific page (e.g., blog post ID)', max_length=100, null=True),
        ),
    ]
