# Generated by Django 5.2.5 on 2025-09-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raj', '0021_blogpost_image_1_base64_blogpost_image_2_base64_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded main image data', null=True),
        ),
    ]
