# Generated by Django 5.2.5 on 2025-09-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raj', '0022_blogpost_image_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='openhouse',
            name='features',
            field=models.TextField(blank=True, help_text='Property features (one per line, e.g., Updated Kitchen, Hardwood Floors, Large Backyard)'),
        ),
    ]
