# Generated by Django 5.2.5 on 2025-09-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raj', '0023_openhouse_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('buying_guide', 'Buying Guide'), ('selling_tips', 'Selling Tips'), ('market_analysis', 'Market Analysis'), ('investment', 'Investment'), ('finance', 'Finance')], default='buying_guide', help_text='Blog post category', max_length=20),
        ),
    ]
