# Generated by Django 5.1.2 on 2025-12-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raj', '0024_blogpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='openhouse',
            name='open_house_end_time',
            field=models.TimeField(blank=True, help_text='End time of the open house', null=True),
        ),
        migrations.AlterField(
            model_name='openhouse',
            name='open_house_time',
            field=models.TimeField(help_text='Start time of the open house'),
        ),
    ]
