# Generated by Django 5.1.2 on 2025-12-20 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raj', '0026_propertylisting_property_status_listing_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Community name (e.g., Katy, Sugar Land)', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly name (auto-generated if blank)', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Community description and highlights')),
                ('image_file', models.ImageField(blank=True, help_text='Upload community image', null=True, upload_to='communities/')),
                ('image_url', models.URLField(blank=True, help_text='Alternative: Community image URL', max_length=500)),
                ('image_base64', models.TextField(blank=True, help_text='Base64 encoded image data', null=True)),
                ('featured', models.BooleanField(default=False, help_text='Featured communities appear on home page')),
                ('published', models.BooleanField(default=True, help_text='Only published communities are visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Communities',
                'ordering': ['-featured', 'name'],
            },
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='community',
            field=models.ForeignKey(blank=True, help_text='Community/neighborhood this property belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='Raj.community'),
        ),
    ]
