# Generated by Django 4.2.7 on 2025-12-20 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Raj', '0027_community_propertylisting_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload property video file (MP4, WebM, etc.)', null=True, upload_to='properties/videos/'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='video_url',
            field=models.URLField(blank=True, help_text='Property video URL (YouTube, Vimeo, or direct video URL)', max_length=500),
        ),
        migrations.CreateModel(
            name='PropertyListingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, help_text='Upload property video file (MP4, WebM, etc.)', null=True, upload_to='properties/videos/')),
                ('video_url', models.URLField(blank=True, help_text='Property video URL (YouTube, Vimeo, or direct video URL)', max_length=500)),
                ('caption', models.CharField(blank=True, help_text='Optional video caption', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary video for the property')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (0 = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Raj.propertylisting')),
            ],
            options={
                'verbose_name': 'Property Listing Video',
                'verbose_name_plural': 'Property Listing Videos',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
