# Generated by Django 4.2.7 on 2025-12-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raj', '0028_propertylisting_video_file_propertylisting_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openhouse',
            name='listing_agent_image',
            field=models.ImageField(blank=True, help_text='Optional image of the listing agent', null=True, upload_to='listing_agents/'),
        ),
        migrations.AddField(
            model_name='openhouse',
            name='listing_agent_link',
            field=models.URLField(blank=True, help_text='Optional URL link for the listing agent (e.g., their profile page)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='openhouse',
            name='listing_agent_name',
            field=models.CharField(blank=True, help_text='Name of the listing agent for courtesy credit', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='listing_agent_link',
            field=models.URLField(blank=True, help_text='Optional URL link for the listing agent (e.g., their profile page)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Full property address', null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Number of bathrooms (can be decimal like 2.5)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='price',
            field=models.CharField(help_text="Price (can be text like 'upper 800s' or numeric)", max_length=100),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='property_status',
            field=models.CharField(choices=[('coming_soon', 'Coming Soon'), ('just_listed', 'Just Listed'), ('for_sale', 'For Sale'), ('for_lease', 'Just Leased'), ('available_for_lease', 'For Lease'), ('under_contract', 'Under-Contract'), ('just_sold', 'Just Sold')], default='for_sale', help_text='Marketing status of the listing', max_length=20),
        ),
    ]
