# Generated by Django 4.2.7 on 2026-01-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raj', '0029_openhouse_listing_agent_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_agent_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_agent_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
