# Generated by Django 4.2.7 on 2026-01-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raj', '0030_property_listing_agent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listing_agent_name',
            field=models.CharField(help_text='Name of the listing agent', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_agent_url',
            field=models.URLField(help_text='URL of the listing agent', null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='listing_agent_name',
            field=models.CharField(default='Raj Gupta', help_text='Name of the listing agent for courtesy credit', max_length=200),
        ),
    ]
