# Generated by Django 5.1.2 on 2026-01-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raj', '0031_alter_property_listing_agent_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='listing_agent_name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='listing_agent_url',
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='listing_agent_name',
            field=models.CharField(help_text='Name of the listing agent for courtesy credit (required)', max_length=200),
        ),
    ]
