# Generated by Django 5.1.2 on 2026-01-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raj', '0031_alter_property_listing_agent_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Inquirer's full name", max_length=100)),
                ('email', models.EmailField(help_text="Inquirer's email address", max_length=254)),
                ('phone', models.CharField(help_text="Inquirer's phone number", max_length=20)),
                ('message', models.TextField(blank=True, help_text='Additional details or requirements (Optional)', null=True)),
                ('source_page', models.CharField(default='General', help_text='Page from which the inquiry was submitted', max_length=200)),
                ('is_contacted', models.BooleanField(default=False, help_text='Check this box when you have contacted the person back')),
                ('admin_notes', models.TextField(blank=True, help_text="Internal notes (e.g., 'Called at 5pm, asked to call back later')", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'General Inquiry',
                'verbose_name_plural': 'General Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='listing_agent_name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='listing_agent_url',
        ),
        migrations.AlterField(
            model_name='linktracking',
            name='page_type',
            field=models.CharField(choices=[('blog', 'Blog Post'), ('buy', 'Buy/Lease Page'), ('sell', 'Selling Page'), ('open_house', 'Open House'), ('mortgage', 'Mortgage Calculator'), ('home', 'Home Page'), ('contact', 'Contact Page'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('terms', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('cookies', 'Cookie Policy')], help_text='Type of page being tracked', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='listing_agent_name',
            field=models.CharField(help_text='Name of the listing agent for courtesy credit (required)', max_length=200),
        ),
    ]
