# Generated by Django 5.1.2 on 2026-01-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raj', '0032_remove_property_listing_agent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linktracking',
            name='page_type',
            field=models.CharField(choices=[('blog', 'Blog Post'), ('buy', 'Buy/Lease Page'), ('sell', 'Selling Page'), ('open_house', 'Open House'), ('mortgage', 'Mortgage Calculator'), ('home', 'Home Page'), ('contact', 'Contact Page'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('terms', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('cookies', 'Cookie Policy')], help_text='Type of page being tracked', max_length=20),
        ),
    ]
