# Generated by Django 5.1.2 on 2026-01-13 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Raj', '0032_generalinquiry_remove_property_listing_agent_name_and_more'),
        ('Raj', '0033_alter_linktracking_page_type'),
    ]

    operations = [
    ]
