"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
from dotenv import load_dotenv

# Load environment variables from .env file
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-tzk4^_u^x05juz(7r*c16hptg0pt6kcwiide^wsg+s+-kfb%&6')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'False
# For local development, enable DEBUG
if os.getenv('ENVIRONMENT') != 'production':
    DEBUG = False

# Check if running on Vercel
#IS_VERCEL = os.getenv('VERCEL', 'false').lower() == 'true'

# Get allowed hosts from environment or use a default list
#ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,.vercel.app,.onrender.com').split(',')
ALLOWED_HOSTS = ['rajtexas.com', 'www.rajtexas.com']
# Add localhost for local development
if DEBUG:
    ALLOWED_HOSTS.extend(['localhost', '127.0.0.1', '*'])

# For development, you can add more hosts
#if DEBUG:
#    ALLOWED_HOSTS.extend(['*'])

# Add common deployment domains
#ALLOWED_HOSTS.extend([
#    'raj-realestate.vercel.app',
#    'raj-realestate-git-main-kumarsravan2004gmailcoms-projects.vercel.app',
#    'raj-realestate-m8ms2xjy1-kumarsravan2004gmailcoms-projects.vercel.app',
#    'henry-realestate.onrender.com'
#])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.humanize',

    'tailwind',
    'theme',
 #   'django_browser_reload',

    'Raj',
    # 'storages',  # Only needed for AWS S3 storage
]

TAILWIND_APP_NAME = 'theme'

INTERNAL_IPS = [
    "127.0.0.1",
]

NPM_BIN_PATH = "C:/Program Files/nodejs/npm.cmd"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
#    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'Raj.middleware.LinkTrackingMiddleware',  # Custom link tracking middleware - temporarily disabled

#    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

if DEBUG:
        INSTALLED_APPS += ['django_browser_reload']
        MIDDLEWARE += ['django_browser_reload.middleware.BrowserReloadMiddleware']



ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Database configuration
import dj_database_url

# Check if DATABASE_URL is available
database_url = os.getenv('DATABASE_URL')

# For local development (DEBUG=True), always use SQLite
# For production, use PostgreSQL if DB_NAME is set
if DEBUG:
    # Use SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
elif os.getenv('DB_NAME'):
    # Use PostgreSQL for production
    DATABASES = {
        'default': {
		'ENGINE': 'django.db.backends.postgresql',
		'NAME': os.getenv('DB_NAME'),
		'USER': os.getenv('DB_USER'),
		'PASSWORD': os.getenv('DB_PASSWORD'),
		'HOST': os.getenv('DB_HOST'),
		'PORT': os.getenv('DB_PORT', '5432'),
	}
    }
else:
    # Fallback to SQLite if no DB_NAME is set
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'  # US Central Time (CDT/CST)

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

#STATIC_URL = '/static/'
#STATICFILES_DIRS = [
#    BASE_DIR / "static",
#]
#STATIC_ROOT = BASE_DIR / "staticfiles"

# Static files configuration for production
#if not DEBUG:
#    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
    
# WhiteNoise configuration
#STATICFILES_FINDERS = [
#    'django.contrib.staticfiles.finders.FileSystemFinder',
#    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
#]

# Media files configuration
#MEDIA_URL = '/media/'
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Production media serving configuration
#if not DEBUG:
    # In production, we need to serve media files through Django
    # This is not ideal for production but works for Render
#    MEDIA_URL = '/media/'
    # Add media serving to URL patterns in production

#STATIC_ROOT = BASE_DIR / "staticfiles"
#STATICFILES_DIRS = [BASE_DIR / "static"]
#STATIC_ROOT = BASE_DIR / "staticfiles_dummy"
#STATIC_ROOT = BASE_DIR / "staticfiles"



#AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID", default=None)
#AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY", default=None)
#AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME", default=None)
#AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME", default=None)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Brand Configuration
# BRAND_NAME = os.getenv('BRAND_NAME', 'raj texas')
BRAND_NAME = 'Raj Realty Texas'
# Debug: Print what we're getting
# print(f"SETTINGS DEBUG: BRAND_NAME from env = {repr(os.getenv('BRAND_NAME'))}")
# print(f"SETTINGS DEBUG: BRAND_NAME final value = {repr(BRAND_NAME)}")

# Logging configuration for debugging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Admin site configuration
ADMIN_SITE_HEADER = "raj texas Admin"
ADMIN_SITE_TITLE = "raj texas Admin"
ADMIN_INDEX_TITLE = "raj texas Administration"



# ========================================
# STATIC & MEDIA CONFIGURATION 
# ========================================

from decouple import config
import os
BASE_DIR = Path(__file__).resolve().parent.parent

# --- AWS S3 Settings ---
AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID", default=None)
AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY", default=None)
AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME", default=None)
AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME", default="eu-north-1")

# Use AWS S3 only if credentials are provided and not in DEBUG mode
USE_S3 = AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_STORAGE_BUCKET_NAME and not DEBUG

if USE_S3:
    AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_OBJECT_PARAMETERS = {
        "ACL": "private",  # explicitly safe for ACL-disabled buckets
    }
    
    # --- STATIC FILES ---
    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"
    STATICFILES_DIRS = [
        BASE_DIR / "static",
    ]
    STATIC_ROOT = BASE_DIR / "staticfiles"  # DO NOT COMMENT THIS
    
    # --- MEDIA FILES ---
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"
    
    STORAGES = {
        "default": {
            "BACKEND": "mysite.storage_backends.MediaStorage",
        },
        "staticfiles": {
            "BACKEND": "mysite.storage_backends.StaticStorage",
        },
    }
else:
    # Local development - use local file storage
    STATIC_URL = '/static/'
    STATICFILES_DIRS = [
        BASE_DIR / "static",
    ]
    STATIC_ROOT = BASE_DIR / "staticfiles"
    
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
